### ISSUE TITLE
First day's series of ratings may have significant impact on initial stability

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/short-term-memory-research#2]
![image](https://github.com/open-spaced-repetition/short-term-memory-research/assets/32575846/b3e75025-7bc2-4d53-8d0a-79db14f1addc)

![image](https://github.com/open-spaced-repetition/short-term-memory-research/assets/32575846/9be27891-8ad8-45e3-9769-18970205aa89)

![image](https://github.com/open-spaced-repetition/short-term-memory-research/assets/32575846/e061d40a-be0d-4e7e-8ebf-a37f43fa5f36)

![image](https://github.com/open-spaced-repetition/short-term-memory-research/assets/32575846/5464335d-959e-41e5-ace7-18d4ac82267d)

![image](https://github.com/open-spaced-repetition/short-term-memory-research/assets/32575846/6ee5a441-1850-4c76-8af7-f7a4b6d13fb7)

For more details, please see https://github.com/open-spaced-repetition/short-term-memory-research/tree/main/first_forgetting_curve

@Expertium you may be interested in it.

**Comment by Expertium** [comment]
It's definitely interesting, but how would we utilize this in practice?

**Comment by Vilhelm-Ian** [comment]
could a new parameter be introduced?

**Comment by Expertium** [comment]
When initial stability is chosen, it can only be based on one review because we can't peek into the future. We can't use future data, it's literally impossible. That's why I said that while this is an interesting discovery, I fail to see how we could use it to improve the algorithm.

**Comment by Expertium** [comment]
Actually, wait. We could do a post hoc correction. @L-M-Sherlock, what if the value of S0 is chosen based on the first review, but then as more data comes in, we adjust S0 for this specific card and re-calculate all DSR values? In other words, rather than making S0 a constant, we update our best guess of S0 after each review.
This would be difficult to implement, however. This would mean that the curve-fitting part has to be done after every review, not just once. And it would also mean that the algorithm now has to go through the card's entire history after each review, because DSR values have to be recalculated every time after updating our estimate of S0.
EDIT: since the curve-fitting part would have to be done after every review, this means that the scheduler would have to have access to the full review history of all cards of this preset. So this can't be implemented in Anki, not without major changes.

**Comment by Vilhelm-Ian** [comment]
> When initial stability is chosen, it can only be based on one review because we can't peek into the future. We can't use future data, it's literally impossible. That's why I said that while this is an interesting discovery, I fail to see how we could use it to improve the algorithm.

I interepreted delta_t as hours that passed since last review. I thought all the reviewes were in the same day

**Comment by Expertium** [comment]
No, delta_t is days. This is a bit difficult to explain, but basically what Sherlock did is he grouped reviews based on series of grades. For example:
1) Good
2) Good, Good
3) Again, Good
4) Good, Good, Good
etc.

And what he found is that initial stability is different in different series.

**Comment by L-M-Sherlock** [comment]
> It's definitely interesting, but how would we utilize this in practice?

I will do more research here when I'm more available.

**Comment by L-M-Sherlock** [comment]
Considered in https://github.com/open-spaced-repetition/fsrs-optimizer/pull/81
